spring:
  application:
    name: camel-demo
  main:
    allow-bean-definition-overriding: true
camel:
  springboot:
    main-run-controller: true
customer-inventory-service:
  rest-config:
    component-name: jetty
    host: 0.0.0.0
    port: 8888
  consumes: application/xml
  produces: application/json
  url: http://localhost:8081/customers
  input-path: /customer
  validations:
    customer-request-validation: routings/customer/customer-request.xsd
    customer-response-validation: routings/customer/customer-response.xsd